# Generated by Django 3.0.3 on 2020-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='srcyoubute',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
