# Generated by Django 3.0.3 on 2020-05-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_race_srcyoubute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='srcyoubute',
            new_name='srcyoutube',
        ),
    ]
